# Generated by Django 5.2.7 on 2025-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addadmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('course_opted', models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C & C++', 'C & C++'), ('Dot-Net', 'Dot-Net')], default='Python', max_length=50)),
                ('Registration_fee', models.IntegerField()),
            ],
        ),
    ]
